name: CopyToS3

on:
  push:
    branches:
      - main
  delete:
    branches:
      - main

jobs:
  to_s3:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master 

      - name: Install Dependencies
        run: |
          yarn install

      - name: Build
        run:  |
          yarn build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --recursive --region ap-northeast-1 dist s3://diary-by-yappi
